### ISSUE TITLE
can't support   "cz-customizable": {     "config": "config/path/to/my/config.js"   } in package.json?

### ISSUE THREAD

**Issue by hxfdarling** [whizark/commitlint-config-cz#4]
"cz-customizable": {
    "config": "node_modules/path/to/my/config.js"
  }

not support ? only support root dir in project 'cz-config.js' ?

**Comment by whizark** [comment]
> not support ? only support root dir in project 'cz-config.js' ?

Yes, only the `.cz-config.js` in the project root dir is supported for now...

**Comment by hxfdarling** [comment]
I have made the changes to support. Can you merge into the master and release a new version?
